/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.PgmImage;

/**
 *
 * @author wlima
 */
public class IUMain extends javax.swing.JFrame {
    PgmImage img;
    /**
     * Creates new form IUMain
     */
    public IUMain() {
        initComponents();
        
        menuDisable();
    }
    
    // Disable item menu
    public void menuDisable() {
        menuNegative.setEnabled(false);
        menuDarkenI.setEnabled(false);
        menuDarkenII.setEnabled(false);
        menuItemAdd.setEnabled(false);
        menuItemMult.setEnabled(false);
        menuItemRight.setEnabled(false);
        menuItemLeft.setEnabled(false);
        menuItemHorizontal.setEnabled(false);
    }
    
    // Enable item menu
    public void menuEnable() {
        menuNegative.setEnabled(true);
        menuDarkenI.setEnabled(true);
        menuDarkenII.setEnabled(true);
        menuItemAdd.setEnabled(true);
        menuItemMult.setEnabled(true);
        menuItemRight.setEnabled(true);
        menuItemLeft.setEnabled(true);
        menuItemHorizontal.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuNegative = new javax.swing.JMenuItem();
        menuDarkenI = new javax.swing.JMenuItem();
        menuDarkenII = new javax.swing.JMenuItem();
        menuLighten = new javax.swing.JMenu();
        menuItemAdd = new javax.swing.JMenuItem();
        menuItemMult = new javax.swing.JMenuItem();
        menuRotate = new javax.swing.JMenu();
        menuItemRight = new javax.swing.JMenuItem();
        menuItemLeft = new javax.swing.JMenuItem();
        menuItemHorizontal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        menuOpen.setText("Open");
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        jMenu1.add(menuOpen);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("to Darken");

        menuNegative.setText("Negative");
        menuNegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNegativeActionPerformed(evt);
            }
        });
        jMenu2.add(menuNegative);

        menuDarkenI.setText("by value");
        menuDarkenI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDarkenIActionPerformed(evt);
            }
        });
        jMenu2.add(menuDarkenI);

        menuDarkenII.setText("by division");
        menuDarkenII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDarkenIIActionPerformed(evt);
            }
        });
        jMenu2.add(menuDarkenII);

        jMenuBar1.add(jMenu2);

        menuLighten.setText("to Lighten");

        menuItemAdd.setText("add value");
        menuItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddActionPerformed(evt);
            }
        });
        menuLighten.add(menuItemAdd);

        menuItemMult.setText("multiply floating point");
        menuItemMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMultActionPerformed(evt);
            }
        });
        menuLighten.add(menuItemMult);

        jMenuBar1.add(menuLighten);

        menuRotate.setText("to Rotate");

        menuItemRight.setText("right (90º)");
        menuItemRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRightActionPerformed(evt);
            }
        });
        menuRotate.add(menuItemRight);

        menuItemLeft.setText("left (-90º)");
        menuItemLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLeftActionPerformed(evt);
            }
        });
        menuRotate.add(menuItemLeft);

        menuItemHorizontal.setText("horizontal (180º)");
        menuItemHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHorizontalActionPerformed(evt);
            }
        });
        menuRotate.add(menuItemHorizontal);

        jMenuBar1.add(menuRotate);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
        String filename = "";
        FileInputStream f;
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "PNG & PGM Images", "png", "pgm");
        chooser.setFileFilter(filter);
        
        int returnVal = chooser.showOpenDialog(null);
        
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            filename = chooser.getSelectedFile().getAbsolutePath();
            System.out.println("You chose to open this file: " +
                    filename);
            
            menuEnable();
        }
        
        img = new PgmImage(filename);
        
        JOptionPane.showMessageDialog(null, "Imagem Aberta com Sucesso !\n");
    }//GEN-LAST:event_menuOpenActionPerformed

    private void menuNegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNegativeActionPerformed
        try {
            img.convertToNegative();
            JOptionPane.showMessageDialog(null, "A imagem foi convertida para o negativo com sucesso !\n");
        } catch (IOException ex) {
            Logger.getLogger(IUMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuNegativeActionPerformed

    private void menuDarkenIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDarkenIActionPerformed
        int valor = Integer.parseInt(JOptionPane.showInputDialog("Digite um valor para escurecer !\n"));
        try {
            img.convertToDarkenI(valor);
            JOptionPane.showMessageDialog(null, "A imagem foi escurecida sub o valor com sucesso !\n");
        } catch (IOException ex) {
            Logger.getLogger(IUMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuDarkenIActionPerformed

    private void menuDarkenIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDarkenIIActionPerformed
        int value = Integer.parseInt(JOptionPane.showInputDialog("Digite um valor para escurecer !\n"));
        try {
            img.convertToDarkenII(value);
            JOptionPane.showMessageDialog(null, "A imagem foi escurecida através da div do valor com sucesso !\n");
        } catch (IOException ex) {
            Logger.getLogger(IUMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuDarkenIIActionPerformed

    private void menuItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddActionPerformed
        int value = Integer.parseInt(JOptionPane.showInputDialog("Digite um valor para clarear !\n"));
        try {
            img.convertToLightenByAddValue(value);
            JOptionPane.showMessageDialog(null, "A imagem foi clareada com sucesso !\n");
        } catch (IOException ex) {
            Logger.getLogger(IUMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemAddActionPerformed

    private void menuItemMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMultActionPerformed
        int value = Integer.parseInt(JOptionPane.showInputDialog("Digite um valor para clarear !\n"));
        try {
            img.convertToLightenByMultValue(value);
            JOptionPane.showMessageDialog(null, "A imagem foi clareada com sucesso !\n");
        } catch (IOException ex) {
            Logger.getLogger(IUMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemMultActionPerformed

    private void menuItemRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRightActionPerformed
        try {
            img.rotateRight();
            JOptionPane.showMessageDialog(null, "A imagem foi rotacionada para direita com sucesso (90º) !\n");
        } catch (IOException ex) {
            Logger.getLogger(IUMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemRightActionPerformed

    private void menuItemLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLeftActionPerformed
        try {
            img.rotateLeft();
            JOptionPane.showMessageDialog(null, "A imagem foi rotacionada para esquerda com sucesso (-90º) !\n");
        } catch (IOException ex) {
            Logger.getLogger(IUMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemLeftActionPerformed

    private void menuItemHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHorizontalActionPerformed
        try {
            img.rotateHorizontal();
            JOptionPane.showMessageDialog(null, "A imagem foi rotacionada para horizontalmente com sucesso (180º) !\n");
        } catch (IOException ex) {
            Logger.getLogger(IUMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemHorizontalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuDarkenI;
    private javax.swing.JMenuItem menuDarkenII;
    private javax.swing.JMenuItem menuItemAdd;
    private javax.swing.JMenuItem menuItemHorizontal;
    private javax.swing.JMenuItem menuItemLeft;
    private javax.swing.JMenuItem menuItemMult;
    private javax.swing.JMenuItem menuItemRight;
    private javax.swing.JMenu menuLighten;
    private javax.swing.JMenuItem menuNegative;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenu menuRotate;
    // End of variables declaration//GEN-END:variables
}
